export const GET_CART = 'GET_CART';

export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';

export const GET_CART_FAILURE = 'GET_CART_FAILURE';

export const CLEAR_GET_CART_STATUS = 'CLEAR_GET_CART_STATUS';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';

export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';

export const ADD_PRODUCT_TO_CART_FAILURE = 'ADD_PRODUCT_TO_CART_FAILURE';

export const CLEAR_ADD_PRODUCT_TO_CART_STATUS = 'CLEAR_ADD_PRODUCT_TO_CART_STATUS';

export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART';

export const UPDATE_PRODUCT_IN_CART_SUCCESS = 'UPDATE_PRODUCT_IN_CART_SUCCESS';

export const UPDATE_PRODUCT_IN_CART_FAILURE = 'UPDATE_PRODUCT_IN_CART_FAILURE';

export const CLEAR_UPDATE_PRODUCT_IN_CART_STATUS = 'CLEAR_UPDATE_PRODUCT_IN_CART_STATUS';

export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';

export const DELETE_PRODUCT_FROM_CART_SUCCESS = 'DELETE_PRODUCT_FROM_CART_SUCCESS';

export const DELETE_PRODUCT_FROM_CART_FAILURE = 'DELETE_PRODUCT_FROM_CART_FAILURE';

export const CLEAR_DELETE_PRODUCT_FROM_CART_STATUS = 'CLEAR_DELETE_PRODUCT_FROM_CART_STATUS';

export const CLEAR_CART = 'CLEAR_CART';

export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS';

export const CLEAR_CART_FAILURE = 'CLEAR_CART_FAILURE';

export const CLEAR_CLEAR_CART_STATUS = 'CLEAR_CLEAR_CART_STATUS';

export const REMOVE_CART = 'REMOVE_CART';
