export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const CLEAR_GET_CATEGORIES_STATUS = 'CLEAR_GET_CATEGORIES_STATUS';

export const POST_CATEGORY = 'POST_CATEGORY';

export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';

export const POST_CATEGORY_FAILURE = 'POST_CATEGORY_FAILURE';

export const CLEAR_POST_CATEGORY_STATUS = 'CLEAR_POST_CATEGORY_STATUS';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

export const DELETE_CATEGORY_FAILURE = 'DELETE_CATEGORY_FAILURE';

export const CLEAR_DELETE_CATEGORY_STATUS = 'CLEAR_DELETE_CATEGORY_STATUS';

export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';

export const EDIT_CATEGORY_FAILURE = 'EDIT_CATEGORY_FAILURE';

export const CLEAR_EDIT_CATEGORY_STATUS = 'CLEAR_EDIT_CATEGORY_STATUS';
