export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const CLEAR_GET_CATEGORIES_STATUS = 'CLEAR_GET_CATEGORIES_STATUS';

export const POST_CATEGORIES = 'POST_CATEGORIES';

export const POST_CATEGORIES_SUCCESS = 'POST_CATEGORIES_SUCCESS';

export const POST_CATEGORIES_FAILURE = 'POST_CATEGORIES_FAILURE';

export const CLEAR_POST_CATEGORIES_STATUS = 'CLEAR_POST_CATEGORIES_STATUS';
