export const GET_GUEST_CART = 'GET_GUEST_CART';

export const ADD_PRODUCT_TO_GUEST_CART = 'ADD_PRODUCT_TO_GUEST_CART';

export const UPDATE_PRODUCT_IN_GUEST_CART = 'UPDATE_PRODUCT_IN_GUEST_CART';

export const DELETE_PRODUCT_FROM_GUEST_CART = 'DELETE_PRODUCT_FROM_GUEST_CART';

export const CLEAR_GUEST_CART = 'CLEAR_GUEST_CART';
