export const GET_PRODUCTS = 'GET_PRODUCTS';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';

export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const CLEAR_GET_PRODUCTS_STATUS = 'CLEAR_GET_PRODUCTS_STATUS';

export const GET_PRODUCT = 'GET_PRODUCT';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';

export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

export const CLEAR_GET_PRODUCT_STATUS = 'CLEAR_GET_PRODUCT_STATUS';

export const POST_PRODUCT = 'POST_PRODUCT';

export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';

export const POST_PRODUCT_FAILURE = 'POST_PRODUCT_FAILURE';

export const CLEAR_POST_PRODUCT_STATUS = 'CLEAR_POST_PRODUCT_STATUS';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';

export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';

export const EDIT_PRODUCT_FAILURE = 'EDIT_PRODUCT_FAILURE';

export const CLEAR_EDIT_PRODUCT_STATUS = 'CLEAR_EDIT_PRODUCT_STATUS';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';

export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';

export const CLEAR_DELETE_PRODUCT_STATUS = 'CLEAR_DELETE_PRODUCT_STATUS';
