export const GET_USERS_STATISTICS = 'GET_USERS_STATISTICS';

export const GET_USERS_STATISTICS_SUCCESS = 'GET_USERS_STATISTICS_SUCCESS';

export const GET_USERS_STATISTICS_FAILURE = 'GET_USERS_STATISTICS_FAILURE';

export const CLEAR_GET_USERS_STATISTICS_STATUS = 'CLEAR_GET_USERS_STATISTICS_STATUS';

export const GET_PRODUCTS_STATISTICS = 'GET_PRODUCTS_STATISTICS';

export const GET_PRODUCTS_STATISTICS_SUCCESS = 'GET_PRODUCTS_STATISTICS_SUCCESS';

export const GET_PRODUCTS_STATISTICS_FAILURE = 'GET_PRODUCTS_STATISTICS_FAILURE';

export const CLEAR_GET_PRODUCTS_STATISTICS_STATUS = 'CLEAR_GET_PRODUCTS_STATISTICS_STATUS';
