export const REGISTER = 'REGISTER';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const CLEAR_REGISTER_STATUS = 'CLEAR_REGISTER_STATUS';

export const LOGIN = 'LOGIN';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const CLEAR_LOGIN_STATUS = 'CLEAR_LOGIN_STATUS';

export const LOGOUT = 'LOGOUT';

export const GET_USER = 'GET_USER';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const CLEAR_GET_USER_STATUS = 'CLEAR_GET_USER_STATUS';
