export const REGISTER = 'REGISTER';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const CLEAR_REGISTER_STATUS = 'CLEAR_REGISTER_STATUS';

